### ISSUE TITLE
ideas to improve the UX

### ISSUE THREAD

**Issue by mvdan** [aarzilli/whydeadcode#1]
There isn't a `-h` flag or any usage info, I would include that. Otherwise `whydeadcode -h` just hangs.

The tool doesn't print anything when it "succeeds", meaning that deadcode elimination is fully enabled. This is kinda confusing; at first I doubted whether I was running the tool properly.

The tool doesn't seem to care if the input isn't valid, e.g:

```
$ go build -ldflags=-dumpdep ./cmd/cue
go: build output "cue" already exists and is a directory
$ go build -ldflags=-dumpdep ./cmd/cue |& whydeadcode
$ echo $?
0
```

It should probably fail if the input doesn't have any `-dumpdep` lines.

**Comment by aarzilli** [comment]
> There isn't a `-h` flag or any usage info

I should probably use cobra for that.

**Comment by aarzilli** [comment]
Thanks

**Comment by aarzilli** [comment]
I didn't change what it does when it finds nothing, I'm not sure it should actually print something on success.
