### ISSUE TITLE
`MethodByName` with constant name should be ignored

### ISSUE THREAD

**Issue by pgimalac** [aarzilli/whydeadcode#2]
`whydeadcode` doesn't filter out uses of `MethodByName` with a constant name, eg.:
```
reflect.Value.MethodByName reachable from:
	 github.com/gogo/protobuf/proto.(*unmarshalInfo).computeUnmarshalInfo
	 github.com/gogo/protobuf/proto.(*unmarshalInfo).unmarshal
	[...]
```

This does point to [a call to MethodByName](https://github.com/gogo/protobuf/blob/f67b8970b736e53dbd7d0a27146c8f1ac52f74e5/proto/table_unmarshal.go#L418), but the argument is constant, so it doesn't disable dead code elimination. 

I would expect `whydeadcode` to filter it out, or an explicit mention of this caveat in the README ?

**Comment by aarzilli** [comment]
> This does point to [a call to MethodByName](https://github.com/gogo/protobuf/blob/f67b8970b736e53dbd7d0a27146c8f1ac52f74e5/proto/table_unmarshal.go#L418), but the argument is constant, so it doesn't disable dead code elimination.

Are you sure? I remember this improvement being discussed at some point but I'm not aware that it was ever implemented.

**Comment by pgimalac** [comment]
I believe this is the [issue](https://github.com/golang/go/issues/62257) and the [fix](https://go-review.googlesource.com/c/go/+/522436), implemented in Go 1.22.

Also as anecdotal evidence the binary which uses `MethodByName` with a constant argument mentioned above is 19% smaller (around -7MB) when I remove the last use of `html/template`.

[This CL](https://go-review.googlesource.com/c/go/+/528895) adds logging when full DCE is disabled, maybe that could help ?

**Comment by pgimalac** [comment]
I think you should be able to consider only uses of `Method` or `MethodByName` which are marked with the `ReflectMethod` attribute, IIUC calls with constant arguments don't have the attribute

**Comment by aarzilli** [comment]
> I think you should be able to consider only uses of `Method` or `MethodByName` which are marked with the `ReflectMethod` attribute, IIUC calls with constant arguments don't have the attribute

Thanks, I'll look into it.

**Comment by pgimalac** [comment]
I opened a PR which just doesn't hardcode adding `reflect.Value.MethodByName` and `reflect.Value.Method` in `reflectMethods`, tested on some binaries and it seems to fix the issue.
Let me know if that seems good to you !
